tags  = {
    "preguntaInicio" : "Tiene seis opciones: R(piedra) P(papel) S(tijeras) L(lagarto) K(spock) o... X(Salir)",
    "preguntaError" : "Opcion incorrecta, por favor, escoja R P S L K ó X",
    "jugar" : "¿Que quiere jugar?",
    "empate" : "Empate",
    "ganas" : "Ganas",
    "sales" : "Sales",
    "pierdes" : "Pierdes",
    "piedra" : "Piedra",
    "papel" : "Papel",
    "tijera" : "Tijera",
    "lagarto" : "Lagarto",
    "spock" : "Spock",
    "salir" : "Salir",
    "resultado" : "{resultado}, jugaste: {seleccionJugador} la maquina jugo {seleccionMaquina}",
    "cargo" : "Cargo la partida",
    "guardo" : "Guardo la partida",
    "puntuacion" : "V: {victorias}, E: {empates}, D: {derrotas}",
    "continuar" : "Golpee la tecla ""Enter"" para continuar",
    "tuNombre" : "¿Como quieres que te llame?",
    "resumen" : "Has empezado la partida a las {timeString} y has estado jugando {elapsedTime} segundos"
}